version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test-and-deploy:
    executor: python/default
    steps:
      - checkout  
      - run:
          command: |
            sudo pip install pipenv
            pipenv install -d
      - run:
          command: |
            pipenv run pytest tests/lru_cache_unittests.py
      - run:
          command: |
            pipenv run setup.py sdist bdist_wheel
            twine upload -u __token__ -p $PYPI_PASSWORD --repository testpypi dist/*


workflows:
  main:
    jobs:
      - test-and-deploy